export const PJAX_CONTAINER = '#js-repo-pjax-container, .context-loader-container, [data-pjax-container]'
export const PLUS_SELECTOR = 'g-emoji[alias~="+1"].mr-1'
export const MINUS_SELECTOR = 'g-emoji[alias~="-1"].mr-1'
export const SMILE_SELECTOR = 'g-emoji[alias~="smile"].mr-1'
export const THINKING_SELECTOR = 'g-emoji[alias~="thinking_face"].mr-1'
export const TADA_SELECTOR = 'g-emoji[alias~="tada"].mr-1'
export const HEART_SELECTOR = 'g-emoji[alias~="heart"].mr-1'